# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Notes by Henok
site_url: https://henok.tech/

theme:
  name: material
  palette: 
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

nav:
  - Home: index.md
  - Linux:
    - Overview: Linux/overview.md
    - Command Line: Linux/command_line.md
  - Career:
    - System Administration: Career/sysadmin.md
  - Blog: https://henoktilahun.com/

